[job]
system = [ "nnodes.job", "Frontier",]
name = "Inversion Set"
nnodes = 65
account = "GEO111"
walltime = 120.0
gap = 10.0
debug = false
node_splittable = true

[root]
task = ["cmt3d.ioi.nnodes.inversion", "main",]
inputfile = "/ccs/home/lsawade/gcmt_andes/cmt3d/workflow/nnodes/input.yml"
# inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input_hard_damping.yml"
# inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input_fix_depth_10.yml"
# eventid = "B071402C,B071597B,B071600C,B071896B,B071995A,B072099A,B072100D,B072103F,B072200B,B072200C,B072203B,B072296C,B072300F,B072302D,B072396C,B072400D,B072402B,B072403C,B072496E,B072500A,B072501B,B072501F,B072502B,B072595A,B072603F,B072603H,B072603J,B072695A,B072699D,B072699E,B072700A,B072796B,B072797D,B072800D,B072800G,B072802D,B072803B"
# eventid="B070895A"
# start_index = 0
# end_index = 10
# max_conc = 10
subset_max_conc = 30 # max number of subsets to get simultaneously
inversion_max_conc = 100 # max number of subsets to get simultaneously
start_index = 6250
end_index = 6850
redo = true
redo_keep_subset = false
dbname = "/lustre/orion/geo111/scratch/lsawade/DB/GLAD-M25/128_single"
db_is_local = true
# Multiprocesses: Number of cores to use for the processing
backend = 'mpi' #['multiprocessing', 'mpi']
# Submission parameters
forward_nproc = 56
forward_slurm_flags = "--mem=0 --exclusive -N1"
subset_nproc = 4
subset_slurm_flags = "-N1 --exclusive --mem=0"
process_nproc = 26
window_nproc = 56
save_interval = 30
retry_delay = 10
default_retry = 1
eventchecksleep = 60