[job]
system = [ "nnodes.job", "Summit",]
name = "Inversion Set"
nnodes = 100
account = "GEO111"
walltime = 120.0
gap = 5.0
debug = false
node_splittable = true

[root]
task = ["cmt3d.ioi.nnodes.inversion", "main",]
inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input.yml"
# inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input_hard_damping.yml"
# inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input_fix_depth_10.yml"
# eventid = "B010896B"
# start_index = 0
# end_index = 10
# max_conc = 10
start_index = 40
end_index = 140
redo = true
dbname = "/gpfs/alpine/geo111/scratch/lsawade/DB/GLAD-M25/128_single"
db_is_local = true
# Multiprocesses: Number of cores to use for the processing
backend= 'mpi' #['multiprocessing', 'mpi']
process_nproc = 6
window_nproc = 15
save_interval = 60