[job]
system = ["nnodes.job", "DTN"]
name = "Inversion Test"
nnodes = 1
account = "GEO111"
walltime = 60.0
gap = 2.0
debug = true
node_splittable = true

[root]
# task = ["cmt3d.ioi.nnodes.inversion", "main"]
task = ["cmt3d.ioi.nnodes.download", "main"]
inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input.yml"
max_evenllts = 7
#eventid = "C051200C"
nproc = 20
dbname = "/gpfs/alpine/geo111/scratch/lsawade/DB/GLAD-M25/128_single" # "glad-m25"
db_is_local = true