[job]
system = [ "nnodes.job", "DTN",]
name = "Inversion Test"
nnodes = 1
account = "GEO111"
walltime = 720.0
gap = 2.0
debug = true
node_splittable = true

[root]
task = [ "cmt3d.ioi.nnodes.download", "main",]
inputfile = "/ccs/home/lsawade/gcmt/cmt3d/workflow/nnodes/input.yml"
max_evenllts = 7
nproc = 20
dbname = "/lustre/orion/geo111/scratch/lsawade/DB/GLAD-M25/128_single"
db_is_local = true
save_interval = 60
start_index = 7450
# end_index = 8050
