# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple

__version__ = version = '0.1.0.dev7+g7514ea5.d20230925'  # type: str
__version_tuple__ = version_tuple = (0, 1, 0, 'dev7', 'g7514ea5.d20230925')  # type: Tuple[int | str, ...]
