# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.0.dev1+g8a36cce.d20230914'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev1', 'g8a36cce.d20230914')
